(function(root){
'use strict';
const W=480,H=640,clamp=(n,a,b)=>Math.max(a,Math.min(b,n)),mix=(a,b,t)=>a+(b-a)*t;
const STAGES=Array.from({length:10},(_,i)=>({number:i+1,bonus:i===2||i===6,count:40,speed:1+i*.085,diveInterval:Math.max(.65,2.7-i*.22),maxDivers:Math.min(9,2+Math.floor(i*.8)),bulletSpeed:125+i*15,fireChance:.28+i*.065}));
class Game{
 constructor({random=Math.random,onEvent=()=>{}}={}){this.random=random;this.onEvent=onEvent;this.reset();this.state='title'}
 reset(){this.time=0;this.score=0;this.lives=3;this.stage=1;this.shots=0;this.hits=0;this.kills=0;this.nextLife=20000;this.player={x:240,y:580,dual:false,invincible:2,respawn:0};this.bullets=[];this.enemyBullets=[];this.enemies=[];this.effects=[];this.labels=[];this.fireTimer=0;this.state='playing';this.beginStage()}
 emit(type,data={}){this.onEvent({type,...data})}
 beginStage(){this.config=STAGES[this.stage-1];this.stageTime=0;this.spawned=0;this.stageKills=0;this.escaped=0;this.spawnTimer=1.7;this.diveTimer=4;this.clearTimer=null;this.bullets=[];this.enemyBullets=[];this.enemies=[];this.banner=this.config.bonus?'CHALLENGING STAGE':`STAGE ${String(this.stage).padStart(2,'0')}`;this.bannerTime=2;this.emit('stage',{stage:this.stage,bonus:this.config.bonus})}
 addScore(points){this.score+=points;while(this.score>=this.nextLife){this.lives++;this.nextLife+=70000;this.emit('extraLife');this.label(240,440,'1UP','#91e7a3')}this.emit('score',{score:this.score})}
 label(x,y,text,color='#ffe5a1'){this.labels.push({x,y,text,color,life:1.6})}
 spawn(){const i=this.spawned++,row=i<4?0:i<12?1:i<20?2:i<30?3:4,col=row===0?i:row===1?i-4:row===2?i-12:row===3?i-20:i-30,cols=row===0?4:row<3?8:10;const type=row===0?'boss':row<3?'butterfly':'bee';const side=Math.floor(i/8)%2===0?-1:1;
 this.enemies.push({id:i,type,hp:type==='boss'?2:1,x:side<0?-30:510,y:-25,homeX:240+(col-(cols-1)/2)*36,homeY:105+row*34,side,age:0,mode:'entry',angle:0,shot:false,captive:false,escort:0,beamUsed:false});}
 formation(e){return {x:e.homeX+Math.sin(this.stageTime*1.2)*13+(e.homeX-240)*Math.sin(this.stageTime*.85)*.055,y:e.homeY+Math.sin(this.stageTime*.85)*5}}
 dive(e,escort=0){e.mode='dive';e.age=0;e.sx=e.x;e.sy=e.y;e.target=clamp(this.player.x+(this.random()-.5)*80,35,445);e.shot=false;e.escort=escort;this.emit('dive')}
 fire(){if(this.player.respawn>0)return;const volleys=new Set(this.bullets.map(b=>b.volley));if(volleys.size>=2)return;const volley=this.shots++;for(const dx of this.player.dual?[-13,13]:[0])this.bullets.push({x:this.player.x+dx,y:this.player.y-17,vy:-470,volley});this.emit('fire')}
 shootEnemy(e){if(this.config.bonus||this.player.respawn>0||this.enemyBullets.length>=14)return;const dx=this.player.x-e.x,dy=this.player.y-e.y,len=Math.hypot(dx,dy);if(dy<35)return;this.enemyBullets.push({x:e.x,y:e.y+10,vx:dx/len*this.config.bulletSpeed*.68,vy:Math.max(.65,dy/len)*this.config.bulletSpeed});}
 burst(x,y,color){for(let i=0;i<15;i++){const a=this.random()*Math.PI*2,s=30+this.random()*100;this.effects.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:.3+this.random()*.4,color})}}
 damage(){const p=this.player;if(p.invincible>0||p.respawn>0||this.state!=='playing')return;this.burst(p.x,p.y,'#ffad64');this.emit('damage');if(p.dual){p.dual=false;p.invincible=2.5;this.label(p.x,p.y-40,'SINGLE FIGHTER');return}this.lives--;if(this.lives<=0){this.state='gameover';this.emit('gameover');return}p.respawn=1.5;p.invincible=3;p.x=240;this.enemyBullets=[]}
 capture(e){const p=this.player;if(p.dual||p.respawn>0||p.invincible>0||this.lives<2)return;e.captive=true;e.mode='return';e.age=0;e.sx=e.x;e.sy=e.y;this.lives--;p.respawn=1.6;p.invincible=3;p.x=240;this.enemyBullets=[];this.label(e.x,e.y+45,'FIGHTER CAPTURED','#ff8b96');this.emit('capture')}
 kill(e){e.dead=true;this.stageKills++;this.kills++;const attack=e.mode==='dive'||e.mode==='beam'||e.mode==='return';let points=e.type==='boss'?(attack?400+e.escort*400:150):e.type==='butterfly'?(attack?160:80):(attack?100:50);if(this.config.bonus)points=100;this.addScore(points);this.burst(e.x,e.y,e.type==='boss'?'#8affbd':e.type==='bee'?'#ffe168':'#ff83a0');this.emit('kill');if(e.type==='boss'&&attack)this.label(e.x,e.y,String(points));if(e.captive){if(e.mode==='dive'){this.player.dual=true;this.player.invincible=2;this.label(this.player.x,510,'DUAL FIGHTER!','#81efff');this.emit('rescue')}else{this.enemies.push({id:1000+e.id,type:'rogue',hp:1,x:e.x,y:e.y-24,homeX:e.homeX,homeY:e.homeY-30,side:e.side,age:0,mode:'formation',angle:0,shot:false,captive:false,beamUsed:true});this.label(e.x,e.y,'RESCUE DURING A DIVE','#ff8b96')}}}
 update(dt,input={}){if(this.state!=='playing')return;dt=Math.min(dt,.05);this.time+=dt;this.stageTime+=dt;this.bannerTime-=dt;const p=this.player;p.invincible=Math.max(0,p.invincible-dt);p.respawn=Math.max(0,p.respawn-dt);if(p.respawn<=0){const lo=p.dual?27:15,hi=p.dual?453:465;if(input.axis)p.x=clamp(p.x+input.axis*300*dt,lo,hi);else if(Number.isFinite(input.pointer))p.x=clamp(p.x+clamp(input.pointer-p.x,-440*dt,440*dt),lo,hi);this.fireTimer-=dt;if(this.fireTimer<=0&&this.bannerTime<.7){this.fire();this.fireTimer=.14}}
 this.spawnTimer-=dt;if(this.spawned<40&&this.spawnTimer<=0){this.spawn();this.spawnTimer=(this.spawned%8===0?.9:.16)/this.config.speed}
 const active=this.enemies.filter(e=>!e.dead&&e.mode==='dive').length;this.diveTimer-=dt;if(!this.config.bonus&&this.diveTimer<=0&&active<this.config.maxDivers){const available=this.enemies.filter(e=>e.mode==='formation'&&!e.dead);if(available.length){const e=available[Math.floor(this.random()*available.length)];if(e.type==='boss'&&!e.captive&&!e.beamUsed&&!p.dual&&this.lives>1&&this.random()<.65){e.mode='tractor';e.age=0;e.sx=e.x;e.sy=e.y;e.target=clamp(p.x,70,410);e.beamUsed=true}else{const guards=e.type==='boss'?available.filter(g=>g.type==='butterfly'&&Math.abs(g.x-e.x)<85).slice(0,2):[];this.dive(e,guards.length);for(const g of guards)this.dive(g)} }this.diveTimer=this.config.diveInterval}
 for(const e of this.enemies){if(e.dead)continue;e.age+=dt;const prevX=e.x,prevY=e.y,home=this.formation(e),speed=this.config.speed;
 if(e.mode==='entry'){const t=e.age*speed/2.9;if(this.config.bonus){const u=e.age*speed/3.7;e.x=240+e.side*(300-600*u)+Math.sin(u*Math.PI*4+e.id*.16)*85;e.y=50+Math.sin(Math.min(1,u)*Math.PI)*345;if(u>=1.15){e.dead=true;this.escaped++}}else if(t<.68){const u=t/.68;e.x=240+e.side*(270*(1-u))+Math.sin(u*Math.PI*2)*95;e.y=-25+u*310+Math.sin(u*Math.PI*2)*60}else{const u=clamp((t-.68)/.32,0,1);e.x=mix(240,home.x,u);e.y=mix(285,home.y,u);if(t>=1){e.mode='formation';e.age=0}}}
 else if(e.mode==='formation'){e.x=home.x;e.y=home.y;e.angle=0}
 else if(e.mode==='dive'){const t=e.age*speed/3.4;if(t<.26){const u=t/.26;e.x=e.sx+Math.sin(u*Math.PI*2)*48;e.y=e.sy-55*Math.sin(u*Math.PI)}else{const u=(t-.26)/.74;e.x=mix(e.sx,e.target,clamp(u*1.7,0,1))+Math.sin(u*Math.PI*2)*65;e.y=mix(e.sy,710,u)}if(t>.42&&!e.shot){e.shot=true;if(this.random()<this.config.fireChance)this.shootEnemy(e)}if(t>=1){e.mode='return';e.age=0;e.sx=clamp(e.x,25,455);e.sy=-35}}
 else if(e.mode==='tractor'){const u=clamp(e.age/1.15,0,1);e.x=mix(e.sx,e.target,u);e.y=mix(e.sy,285,u);if(u>=1){e.mode='beam';e.age=0;this.emit('beam')}}
 else if(e.mode==='beam'){e.angle=0;if(e.age>.65&&Math.abs(p.x-e.x)<22&&p.respawn<=0)this.capture(e);if(e.mode==='beam'&&e.age>4.2){e.mode='return';e.age=0;e.sx=e.x;e.sy=e.y}}
 else if(e.mode==='return'){const u=clamp(e.age*speed/1.4,0,1);e.x=mix(e.sx,home.x,u);e.y=mix(e.sy,home.y,u);if(u>=1){e.mode='formation';e.age=0}}
 if(!['formation','beam'].includes(e.mode))e.angle=Math.atan2(e.x-prevX,-(e.y-prevY));
 }
 for(const b of this.bullets){const oldY=b.y;b.y+=b.vy*dt;for(const e of this.enemies){if(e.dead||e.mode==='beam'||e.mode==='tractor'||e.y<0)continue;if(Math.abs(b.x-e.x)<14&&b.y<=e.y+12&&oldY>=e.y-12){b.dead=true;e.hp--;this.hits++;if(e.hp<=0)this.kill(e);else this.emit('hit');break}}}
 for(const b of this.enemyBullets){b.x+=b.vx*dt;b.y+=b.vy*dt;if(p.respawn<=0&&Math.abs(b.x-p.x)<(p.dual?23:10)&&Math.abs(b.y-p.y)<12){b.dead=true;this.damage()}}
 for(const e of this.enemies){if(!e.dead&&p.respawn<=0&&Math.abs(e.x-p.x)<(p.dual?30:18)&&Math.abs(e.y-p.y)<20){this.damage();if(p.invincible<=0)break}}
 this.bullets=this.bullets.filter(b=>!b.dead&&b.y>-20);this.enemyBullets=this.enemyBullets.filter(b=>!b.dead&&b.y<660&&b.x>-20&&b.x<500);this.enemies=this.enemies.filter(e=>!e.dead);
 for(const f of this.effects){f.x+=f.vx*dt;f.y+=f.vy*dt;f.life-=dt}this.effects=this.effects.filter(f=>f.life>0);for(const l of this.labels){l.y-=dt*15;l.life-=dt}this.labels=this.labels.filter(l=>l.life>0);
 if(this.spawned===40&&this.enemies.length===0&&this.clearTimer===null&&this.state==='playing'){this.clearTimer=3;this.enemyBullets=[];if(this.config.bonus){const perfect=this.escaped===0;const bonus=perfect?10000:this.stageKills*100;this.addScore(bonus);this.banner=perfect?'PERFECT!  +10,000':`${this.stageKills} HITS · BONUS ${bonus}`;this.bannerTime=3}else{this.banner='STAGE CLEAR';this.bannerTime=2;this.addScore(this.stage*500)}this.emit('clear')}
 if(this.clearTimer!==null&&this.state==='playing'){this.clearTimer-=dt;if(this.clearTimer<=0){if(this.stage===10){this.state='victory';this.emit('victory')}else{this.stage++;this.beginStage()}}}
 }
}
const api={Game,STAGES,W,H};if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.Arcade=api;
})(typeof globalThis!=='undefined'?globalThis:this);
