'use strict';
(() => {
const $=id=>document.getElementById(id),canvas=$('game'),ctx=canvas.getContext('2d');
const sprites={
 player:['00000100000','00001110000','00001110000','01001110010','01101110110','01111111110','11121112111','11121112111','10001110001','00003030000','00003030000'],
 bee:['00100000100','00010001000','00012221000','00122222100','01123232110','11222222211','11022222011','10001110001','00011011000','00110001100'],
 butterfly:['01000000010','01100000110','01110201110','01122222110','00122322100','00022222000','00122222100','01110201110','01100000110','01000000010'],
 boss:['00100000100','01110001110','11111111111','11221112211','11221112211','01111111110','00013331000','00111111100','01101010110','11001010011','10000000001']};
const palettes={player:['','#e7eff9','#f54d66','#72dbff'],rogue:['','#f76971','#fff','#f4b45a'],bee:['','#fbc944','#ff8b40','#94daff'],butterfly:['','#eb4968','#7cb8ff','#eee7ff'],boss:['','#63d7a7','#84abff','#ea83b8'],hurt:['','#7887ea','#f8a4c9','#eee3bf']};
function sprite(c,type,x,y,scale=2,angle=0,hurt=false){const map=sprites[type==='rogue'?'player':type],pal=palettes[hurt?'hurt':type];c.save();c.translate(Math.round(x),Math.round(y));c.rotate(angle);for(let j=0;j<map.length;j++)for(let i=0;i<map[j].length;i++){const n=+map[j][i];if(n){c.fillStyle=pal[n];c.fillRect((i-5.5)*scale,(j-5.5)*scale,scale,scale)}}c.restore()}
for(const [id,type] of [['enemyBee','bee'],['enemyButterfly','butterfly'],['enemyBoss','boss']])sprite($(id).getContext('2d'),type,22,20,2);
let high=0;try{high=Number(localStorage.getItem('quarter-club-high'))||0}catch{}
let muted=true,audio=null,paused=false,pointer=null,inputSource='keyboard',padWasPressed=false,lastStage=0,lastHigh=-1,visualTime=0;
const keys=new Set(),stars=Array.from({length:95},(_,i)=>({x:(i*173.73)%480,y:(i*97.13)%640,z:.25+(i%4)*.25,color:['#94a8c6','#a98b78','#7489b0','#58769a'][i%4]}));
function tone(freq,duration,shape='square',volume=.03,end=freq){if(muted)return;try{audio ||= new (window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type=shape;o.frequency.setValueAtTime(freq,audio.currentTime);o.frequency.exponentialRampToValueAtTime(Math.max(20,end),audio.currentTime+duration);g.gain.setValueAtTime(volume,audio.currentTime);g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+duration);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+duration)}catch{}}
function onEvent(e){if(e.type==='fire')tone(1100,.06,'square',.012,450);if(e.type==='kill')tone(230,.12,'sawtooth',.027,50);if(e.type==='hit')tone(390,.07,'triangle',.04);if(e.type==='damage')tone(140,.45,'sawtooth',.06,25);if(e.type==='capture')tone(700,.7,'sine',.05,130);if(e.type==='beam')tone(100,.8,'sawtooth',.016,420);if(['rescue','extraLife','clear','victory'].includes(e.type)){[440,554,659,880].forEach((f,i)=>setTimeout(()=>tone(f,.17,'triangle',.06),i*90))}if(e.type==='stage')lastStage=0;if(['gameover','victory'].includes(e.type))showResult(e.type)}
const game=new Arcade.Game({onEvent});
function saveHigh(){if(game.score>high){high=game.score;try{localStorage.setItem('quarter-club-high',String(high))}catch{}}}
function showResult(type){saveHigh();$('overlay').hidden=false;$('overlayKicker').textContent=type==='victory'?'ALL TEN STAGES COMPLETE':'EVERY PILOT GETS ANOTHER CHANCE';$('overlayTitle').textContent=type==='victory'?'VICTORY':'GAME OVER';$('overlayText').replaceChildren();const first=document.createTextNode(`SCORE ${game.score.toLocaleString()} · STAGE ${game.stage}/10`),br=document.createElement('br'),span=document.createElement('span');span.textContent=`격추 ${game.kills}기 · 발사 ${game.shots}회 · ${game.player.dual?'듀얼':'싱글'} 파이터`;$('overlayText').append(first,br,span);$('start').innerHTML='다시 도전 <span>↗</span>';$('enterHint').textContent='PRESS ENTER TO PLAY AGAIN';$('status').textContent=type==='victory'?'MISSION COMPLETE':'RUN COMPLETE'}
function start(){paused=false;keys.clear();pointer=null;$('pausePanel').hidden=true;$('overlay').hidden=true;game.reset();$('status').textContent='MISSION IN PROGRESS';canvas.focus();tone(440,.13,'triangle',.05)}
function pause(force){if(game.state!=='playing')return;paused=typeof force==='boolean'?force:!paused;keys.clear();pointer=null;$('pausePanel').hidden=!paused;$('pause').textContent=paused?'▶':'Ⅱ';$('status').textContent=paused?'PAUSED':'MISSION IN PROGRESS';if(!paused)canvas.focus()}
function toggleSound(){muted=!muted;$('sound').textContent=muted?'SOUND OFF':'SOUND ON';$('sound').setAttribute('aria-pressed',String(!muted));$('sound').setAttribute('aria-label',muted?'사운드 켜기':'사운드 끄기');if(!muted)tone(660,.12,'triangle',.05)}
$('start').onclick=start;$('resume').onclick=()=>pause(false);$('pause').onclick=()=>pause();$('sound').onclick=toggleSound;$('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.querySelector('.cabinet').requestFullscreen()}catch{$('status').textContent='FULLSCREEN UNAVAILABLE'}};
window.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Space'].includes(e.code))e.preventDefault();if(e.repeat)return;if(e.code==='Enter'&&game.state!=='playing'){e.preventDefault();start();return}if(e.code==='KeyP'||e.code==='Escape'){pause();return}if(e.code==='KeyM'){toggleSound();return}keys.add(e.code);if(['ArrowLeft','ArrowRight','KeyA','KeyD'].includes(e.code)){inputSource='keyboard';pointer=null}});
window.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',()=>pause(true));document.addEventListener('visibilitychange',()=>{if(document.hidden)pause(true)});
function movePointer(e){if(e.pointerType==='touch'&&e.type==='pointermove'&&e.buttons===0)return;const rect=canvas.getBoundingClientRect();pointer=(e.clientX-rect.left)/rect.width*480;inputSource='pointer';if(e.type==='pointerdown'){canvas.setPointerCapture(e.pointerId);canvas.focus()}}
canvas.addEventListener('pointermove',movePointer);canvas.addEventListener('pointerdown',movePointer);canvas.addEventListener('pointerleave',()=>{pointer=null});canvas.addEventListener('pointerup',e=>{if(e.pointerType!=='mouse')pointer=null});canvas.addEventListener('pointercancel',()=>{pointer=null});
function getInput(){let axis=(keys.has('ArrowRight')||keys.has('KeyD')?1:0)-(keys.has('ArrowLeft')||keys.has('KeyA')?1:0);let pad;try{pad=Array.from(navigator.getGamepads?.()||[]).find(p=>p?.connected)}catch{}if(pad){const stick=pad.axes[0]||0,padAxis=(pad.buttons[15]?.pressed?1:0)-(pad.buttons[14]?.pressed?1:0)||(Math.abs(stick)>.18?stick:0);if(padAxis){axis=padAxis;inputSource='gamepad';pointer=null}const pressed=!!(pad.buttons[0]?.pressed||pad.buttons[9]?.pressed);if(pressed&&!padWasPressed){if(game.state!=='playing')start();else pause()}padWasPressed=pressed}else padWasPressed=false;return {axis,pointer:inputSource==='pointer'?pointer:null}}
function text(str,x,y,size=12,color='#e7e9ef',align='center'){ctx.font=`${size}px monospace`;ctx.textAlign=align;ctx.fillStyle=color;ctx.fillText(str,x,y)}
function draw(){ctx.fillStyle='#040810';ctx.fillRect(0,0,480,640);for(const s of stars){ctx.globalAlpha=.3+s.z*.6;ctx.fillStyle=s.color;ctx.fillRect(s.x,(s.y+visualTime*(8+s.z*15))%640,s.z>.8?2:1,s.z>.8?2:1)}ctx.globalAlpha=1;
 text('1UP',28,25,11,'#ff795f','left');text(String(game.score).padStart(6,'0'),28,44,17,'#edf0fa','left');text('HIGH SCORE',240,25,10,'#ff795f');text(String(Math.max(high,game.score)).padStart(6,'0'),240,44,17);text('STAGE',450,25,10,'#8e9bb2','right');text(String(game.stage).padStart(2,'0')+' / 10',450,44,13,'#d3dcec','right');ctx.fillStyle='#28303c';ctx.fillRect(20,57,440,1);
 if(game.state==='title'){for(let i=0;i<30;i++){const row=Math.floor(i/10);sprite(ctx,row===0?'boss':row===1?'butterfly':'bee',60+(i%10)*40+Math.sin(visualTime)*8,115+row*36,2,0)}sprite(ctx,'player',240,578,2)}else{
 for(const e of game.enemies){if(e.mode==='beam'){const spread=Math.min(1,e.age/.7);ctx.save();ctx.globalAlpha=.14+Math.sin(visualTime*18)*.05;ctx.fillStyle='#75d5ff';ctx.beginPath();ctx.moveTo(e.x-12,e.y+10);ctx.lineTo(e.x-42*spread,600);ctx.lineTo(e.x+42*spread,600);ctx.lineTo(e.x+12,e.y+10);ctx.closePath();ctx.fill();ctx.globalAlpha=.6;ctx.strokeStyle='#6cd8e6';for(let i=0;i<8;i++){const t=((visualTime*.5+i/8)%1),y=e.y+20+t*(595-e.y);ctx.beginPath();ctx.ellipse(e.x,y,12+30*t,5,0,0,Math.PI*2);ctx.stroke()}ctx.restore()}
 sprite(ctx,e.type,e.x,e.y,2,e.angle,e.type==='boss'&&e.hp===1);if(e.captive)sprite(ctx,'rogue',e.x,e.y-27,2,Math.PI)}
 for(const b of game.bullets){ctx.fillStyle='#d9f5ff';ctx.fillRect(b.x-1,b.y-7,3,12);ctx.fillStyle='#7ebee9';ctx.fillRect(b.x,b.y+5,1,5)}for(const b of game.enemyBullets){ctx.fillStyle='#ff8079';ctx.fillRect(b.x-2,b.y-4,4,8);ctx.fillStyle='#ffdab2';ctx.fillRect(b.x-1,b.y-3,2,3)}
 const p=game.player;if(p.respawn<=0&&game.state!=='gameover'&&(p.invincible<=0||Math.floor(game.time*12)%2===0)){for(const dx of p.dual?[-13,13]:[0])sprite(ctx,'player',p.x+dx,p.y,2);if(p.dual){ctx.fillStyle='#8cdef5';ctx.fillRect(p.x-5,p.y+4,10,3)}}
 for(const f of game.effects){ctx.globalAlpha=Math.min(1,f.life*3);ctx.fillStyle=f.color;ctx.fillRect(f.x,f.y,3,3)}ctx.globalAlpha=1;for(const l of game.labels){ctx.globalAlpha=Math.min(1,l.life*2);text(l.text,l.x,l.y,12,l.color)}ctx.globalAlpha=1;
 if(game.bannerTime>0){text(game.banner,240,325,game.config.bonus?18:23,'#ffe2a0');if(game.banner==='CHALLENGING STAGE')text('NO ENEMY FIRE · AIM FOR PERFECT',240,350,10,'#a5b5d4')}
 }
 ctx.fillStyle='#28303c';ctx.fillRect(20,610,440,1);for(let i=0;i<Math.min(8,Math.max(0,game.lives-1));i++)sprite(ctx,'player',31+i*22,627,1.2);text(game.player.dual?'DUAL FIGHTER':'FIGHTER',230,630,9,game.player.dual?'#89e4f3':'#76839a');text(game.config.bonus?'CHALLENGE':`${String(game.stageKills).padStart(2,'0')} / 40`,452,630,10,'#9faac1','right');
}
function updateUI(){saveHigh();if(lastHigh!==high){$('highScore').textContent=String(high).padStart(6,'0');lastHigh=high}if(lastStage!==game.stage){lastStage=game.stage;$('stageLabel').textContent=String(game.stage).padStart(2,'0');$('stageType').textContent=game.config.bonus?'CHALLENGE':game.stage===10?'FINAL FORMATION':'FORMATION';$('stageDots').replaceChildren(...Array.from({length:10},(_,i)=>{const s=document.createElement('span');s.textContent=i+1;s.className=i+1===game.stage?'current':i+1<game.stage?'done':'';return s}));$('missionText').textContent=game.config.bonus?'적은 공격하지 않습니다. 40기를 모두 격추하면 퍼펙트 보너스 10,000점!':game.stage===10?'마지막 편대입니다. 모든 적을 격추하고 열 번째 전장을 완수하세요.':'편대의 빈틈을 노리세요. 급강하 중인 적은 더 높은 점수를 줍니다.'}$('stageProgress').style.width=`${(game.stageKills+game.escaped)/40*100}%`}
let last=performance.now(),accumulator=0;function frame(now){const elapsed=Math.min((now-last)/1000,.1);last=now;const input=getInput();if(!paused){visualTime+=elapsed;accumulator+=elapsed;while(accumulator>=1/120){game.update(1/120,input);accumulator-=1/120}}else accumulator=0;draw();updateUI();requestAnimationFrame(frame)}requestAnimationFrame(frame);
})();
